version: '3'
services:
  wodt-platform:
    image: ghcr.io/web-of-digital-twins/wodt-platform:2.1.0
    container_name: wodt-platform
    network_mode: host
    environment:
      EXPOSED_PORT: 4000
      PLATFORM_EXPOSED_URL: http://localhost:4000
    healthcheck:
      test: wget http://localhost:4000/wodt || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5m

  ditto-initializer:
    build: ./ditto-initializer/
    container_name: ditto-initializer
    network_mode: host
    environment:
      DITTO_URL: ${DITTO_URL}
      DITTO_USERNAME: ${DITTO_USERNAME}
      DITTO_PASSWORD: ${DITTO_PASSWORD}
    command: /app/createThing.sh

  ditto-wodt-adapter:
    image: ghcr.io/web-of-digital-twins/ditto-wodt-adapter:1.1.1
    container_name: ditto-wodt-adapter
    network_mode: host
    depends_on:
      wodt-platform:
        condition: service_healthy
      ditto-initializer:
        condition: service_completed_successfully
    environment:
      DITTO_URL: ${DITTO_URL}
      DITTO_OBSERVATION_ENDPOINT: ${DITTO_OBSERVATION_ENDPOINT}
      DITTO_USERNAME: ${DITTO_USERNAME}
      DITTO_PASSWORD: ${DITTO_PASSWORD}
      DITTO_THING_ID: wodt:healthcareuser
      YAML_ONTOLOGY_PATH: ./ditto-dts/HealthcareUserDTAdapterSemanticConfiguration.yml
      PLATFORM_URI: http://localhost:4000
      PHYSICAL_ASSET_ID: DOEJHN85L15H123K
      DIGITAL_TWIN_URI: http://localhost:3000
      DIGITAL_TWIN_EXPOSED_PORT: 3000
      DIGITAL_TWIN_VERSION: "1.0.0"
    volumes:
      - ./ditto-dts:/ditto-dts
  
  wldt-digitaltwins:
    build: 
      secrets:
        - gh_packages_username
        - gh_packages_password
      context: ./wldt-dts
    container_name: wldt-digitaltwins
    network_mode: host
    depends_on:
      wodt-platform:
        condition: service_healthy
    environment:
      MISSION_EXPOSED_PORT: 3001
      AMBULANCE_EXPOSED_PORT: 3002
      RESCUER_EXPOSED_PORT: 3003
      MISSION_PLATFORM_URL: http://localhost:4000
      PATIENT_URI: http://localhost:5000/patient
      ORG_GRADLE_PROJECT_ghPackageUsername: ${GITHUB_PACKAGES_USERNAME}
      ORG_GRADLE_PROJECT_ghPackagesPwd: ${GITHUB_PACKAGES_PASSWORD}

  azure-wodt-adapter:
    image: ghcr.io/web-of-digital-twins/azuredt-wodt-adapter:1.0.1
    container_name: azure-wodt-adapter
    network_mode: host
    depends_on:
      wodt-platform:
        condition: service_healthy
    environment:
      EXPOSED_PORT: 5000
      EXPOSED_URL: http://localhost:5000
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_DT_ENDPOINT: ${AZURE_DT_ENDPOINT}
      SIGNALR_NEGOTIATION_URL: ${SIGNALR_NEGOTIATION_URL}
      SIGNALR_TOPIC_NAME: ${SIGNALR_TOPIC_NAME}
      DIGITAL_TWINS_CONFIGURATION_PATH: ./azure-dts/digitalTwinsConfiguration.kts
    volumes:
      - ./azure-dts:/azure-dts

secrets:
  gh_packages_username:
    environment: ${GITHUB_PACKAGES_USERNAME}
  gh_packages_password:
    environment: ${GITHUB_PACKAGES_PASSWORD}

  